spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: 19961117lhh

server:
  port: 8080

actable:
  table:
    auto: update
  model:
    pack: com.example.entity
  database:
    type: mysql